### ISSUE TITLE
Schema from Polygon builder gives error when imported

### ISSUE THREAD

**Issue by 1m1-github** [docknetwork/vc-schemas#6]
Created a schema at https://schema-builder.polygonid.me/builder with the result: https://raw.githubusercontent.com/ETHGlobalNewYork2023-wiki3/wiki3/main/polygonid/RESIDENCE.json

Get an error: https://github.com/ETHGlobalNewYork2023-wiki3/wiki3/blob/main/polygonid/dock.io%20error%20template%20creation.png

PS We are currently hacking at ETHGlobal New York and would appreciate support asap ~ ty
PPS Sorry, did not know where else to ask for support

**Comment by cykoder** [comment]
@1m1-github you haven't created the schema properly in the polygon builder, the context url is set to an invalid one: jsonLdContext": "https://example.com/path/to/file/context.jsonld"

either remove the metadata and try import again or publish it properly from the polygon builder

**Comment by 1m1-github** [comment]
thank you. i had not published, only saved to JSON
